import type { Meta, StoryObj } from '@storybook/html';

const meta: Meta = {
  title: 'Components/DatePicker',
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component: 'A customizable date picker component with calendar navigation, date selection, and accessibility features.'
      }
    }
  },
  argTypes: {
    id: {
      control: 'text',
      description: 'Unique identifier for the date picker'
    },
    defaultDate: {
      control: 'date',
      description: 'Default selected date'
    },
    minDate: {
      control: 'date',
      description: 'Minimum selectable date'
    },
    maxDate: {
      control: 'date',
      description: 'Maximum selectable date'
    },
    disabledDates: {
      control: 'object',
      description: 'Array of disabled dates'
    }
  }
};

export default meta;
type Story = StoryObj;

export const Default: Story = {
  render: (args) => {
    const container = document.createElement('div');
    container.className = 'story-container';
    container.style.padding = '2rem';
    container.style.minHeight = '500px';

    const datePicker = document.createElement('div');
    datePicker.id = args.id || 'date-picker-default';
    datePicker.className = 'aural-date-picker';
    datePicker.innerHTML = `
      <input
        type="text"
        class="aural-date-picker__input input"
        placeholder="Select a date"
        readonly
      />
      <div class="aural-date-picker__calendar" hidden>
        <div class="aural-date-picker__header">
          <button
            type="button"
            class="aural-date-picker__nav aural-date-picker__nav--prev"
            aria-label="Previous month"
          >
            ‹
          </button>
          <div class="aural-date-picker__current">
            <span class="aural-date-picker__month">February</span>
            <span class="aural-date-picker__year">2026</span>
          </div>
          <button
            type="button"
            class="aural-date-picker__nav aural-date-picker__nav--next"
            aria-label="Next month"
          >
            ›
          </button>
        </div>
        <div class="aural-date-picker__days">
          <div class="aural-date-picker__weekday">Su</div>
          <div class="aural-date-picker__weekday">Mo</div>
          <div class="aural-date-picker__weekday">Tu</div>
          <div class="aural-date-picker__weekday">We</div>
          <div class="aural-date-picker__weekday">Th</div>
          <div class="aural-date-picker__weekday">Fr</div>
          <div class="aural-date-picker__weekday">Sa</div>
        </div>
        <div class="aural-date-picker__dates" role="grid">
          <!-- Dates will be generated by JavaScript -->
        </div>
        <div class="aural-date-picker__footer">
          <button type="button" class="btn btn-sm btn-ghost">Today</button>
          <button type="button" class="btn btn-sm btn-ghost">Clear</button>
        </div>
      </div>
    `;

    container.appendChild(datePicker);

    // Initialize the date picker after a short delay to ensure DOM is ready
    setTimeout(() => {
      if (typeof window.Aural !== 'undefined') {
        window.Aural.initDatePicker(datePicker.id, {
          defaultDate: args.defaultDate,
          minDate: args.minDate,
          maxDate: args.maxDate,
          disabledDates: args.disabledDates || []
        });
      }
    }, 100);

    return container;
  },
  args: {
    id: 'date-picker-default'
  }
};

export const WithDefaultDate: Story = {
  ...Default,
  args: {
    id: 'date-picker-with-default',
    defaultDate: new Date(2026, 1, 27) // February 27, 2026
  }
};

export const WithMinMax: Story = {
  ...Default,
  args: {
    id: 'date-picker-min-max',
    minDate: new Date(2026, 1, 1),
    maxDate: new Date(2026, 1, 28)
  }
};

export const WithDisabledDates: Story = {
  ...Default,
  args: {
    id: 'date-picker-disabled',
    disabledDates: [
      new Date(2026, 1, 5),
      new Date(2026, 1, 12),
      new Date(2026, 1, 19),
      new Date(2026, 1, 26)
    ]
  }
};
